### ISSUE TITLE
Need ability for existing apps to be moved to new auth app

### ISSUE THREAD

**Issue by elhansen748** [concur/developer.concur.com#1223]
The App Creation Tool needs to be updated so that it can create a new auth app from an existing old-auth app. For example, if Boeing has an old-auth app with the expense report and itinerary scope, a user of the tool should be able to have a new auth app created automatically with the same scopes.

In order to accomplish this, the App Creation Tool needs to be updated to:

- [ ] Have an import link where a user can indicate that they have an existing old-auth app that needs to have a new-auth app equivalent created (see screenshot from @haydenlam)
- [ ]  Since the user will be logged in with their CTE account, we should be able to find and return all old-auth apps that exist for that account. These need to be presented to the user so that the user can select which app should have a new auth equivalent created for it. When the user selects one of their old-auth apps, the form to create a new app should be filled out for the user with the details of the old app.
- [ ]  The new auth app should be created automatically from the details of the old-auth app (scopes should match (and should ALWAYS include 'openid'), allowed principal should be set to the client's company, grant types should be password, client credentials, refresh_token and authorization_code by default, and 'owner' should be set to the UUID of the logged in user.
- [ ]  The clientid and secret of the new auth app should be displayed to the user in the same way that it is if the user created the app from scratch in the App Creation Tool. The secret should only be returned to the user but not stored in any database. If the user forgets the secret, they need to generate a new one.

**Comment by haydenlam** [comment]
In order to create a New-Auth App with an existing Old-Auth App. The user must obtain the Old App Consumer Key. This can be found under https://www.concursolutions.com -> Administrator -> Company -> Web Services -> Register Partner Application -> Old Auth App -> Key.

The user will copy and paste this key into the New App Creation Tool under the "Import Old Auth Application" field. When the user press the "Import" button adjacent to the field. The following will be imported to the tool and auto-populate the app creation form.
1. Name
2. Description
3. Scopes
4. Grants (password and refresh_token)
5. Legacy App ID

The app is not created until the user presses the Submit button as if they filled out the form manually.

**Comment by haydenlam** [comment]
Moved to https://github.com/concur/developer.concur.com-forms
