### ISSUE TITLE
Change header on forums

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#212]
Change header for forum on Discourse to:
* Concur logo returns user to developer.concur.com (added header on top of existing header)
* Secondary header text "Forums" returns user to forum home

See attached for specifics:
[Dev Forums.pdf](https://github.com/concur/developer.concur.com/files/96440/Dev.Forums.pdf)

**Edit**
Above pdf converted to png for quick reference.
![devforums](https://cloud.githubusercontent.com/assets/6178896/12526880/6d348a9a-c127-11e5-9241-586cc1b1f15e.png)

**Comment by ncronquist** [comment]
First off, I haven't made any production changes yet, but here is my current plan.

I added a new CSS and HTML Customization [here](http://forum.developer.concur.com/admin/customize/css_html/3/css). This customization adds the Concur logo and text "Developer Center" with a link to developer.concur.com. You can check it out by clicking the `preview` link.

So far, I have not found a way to add the text "Forums" in place of the current Concur logo. This is set by the `logo url` [here](http://forum.developer.concur.com/admin/site_settings/category/required). The logo url specifies the logo image at the top left of your site. If left blank, the site title text will be shown. Currently, our site title text is `Concur Developer Forum`. In order to work around this, I created an image containing the word `Forums` and uploaded it [here](http://forum.developer.concur.com/t/assets-for-the-site-design/7). We could replace the current `logo url` with the url for the `Forums` image, but I can't find any way to preview this change.

**Comment by henryyamamoto-concur** [comment]
The header looks good. If the Forums image will show up below the header, we can go for it. We can always revert it back if it doesn't appear the way we think it will.

Anyone one want to do a sanity check on Nick's changes?

BTW, you don't know how awesome it is to have folks working on this stuff in the backlog.

**Comment by nicklathe** [comment]
@henryyamamoto-concur, it appears I don't have access to these pages for a sanity check. Am I doing something wrong, or do I need special privileges?

**Comment by henryyamamoto-concur** [comment]
There was a five admin limit. I revoked Roger and gave it to you for now.

**Comment by nicklathe** [comment]
Cool I can see it now. I think the changes look good. Seems like the image of "Forums" will work just fine.

**Comment by henryyamamoto-concur** [comment]
Push it. Push it real good.

**Comment by nicklathe** [comment]
:shipit:

**Comment by ncronquist** [comment]
Ok, changes have been made. The image `Forums` seems like the text is a little darker than the gray used for `Developer Center`. Let me know what you think @henryyamamoto-concur.

**Comment by henryyamamoto-concur** [comment]
Additional fit n finish, if possible, is to add some padding in the header so there's more white space. What I'm trying to accomplish is to have the logo appear to move less from Forums to Dev Center site.

**Comment by ncronquist** [comment]
I added some margin to the top so now the two logos seem to be on the same vertical row. I'll do some looking to see how difficult it would be to get them on the same horizontal column.

**Comment by ncronquist** [comment]
- Added a new CSS customization to increase the max-width site wide from 1110px to 1140px 
    - Seems to have aligned the `Concur Developer Center` headers pretty close
    - Appears to work well with multiple screen sizes 
- Made some super small CSS changes to the Discourse Concur Developer Center logo to make it match up a little better with the Concur Developer Center logo

Let me know if you see any issues.

**Comment by nicklathe** [comment]
Yeah, the new max-width setting gets us super close. Looks good to me - :shipit:. I say we let @henryyamamoto-concur give it the final approval before merging.
