### ISSUE TITLE
Import existing Swagger into developer.concur.com

### ISSUE THREAD

**Issue by howarddierking** [concur/developer.concur.com#280]
Currently, the swagger UI documentation for the site is running code on https://api.concursolutions.com/api/docs/index.html. There's no real reason for this to be implemented as a compute-bound resource as the whole idea of a Swagger interface is to remain stable once published.

We should then plan on extracting the Swagger JSON from the current endpoint and then generate the swagger UI as static resources as a part of the Jekyll build process.

Note that the exported swagger will need to be first cleaned up as the current generator produces invalid swagger.

**Comment by henryyamamoto-concur** [comment]
**In terms of priority:**
1. Get documentation up and running
2. Get testing/explorer functionality back up (enter token, make test calls, etc.)

Until we figure out the IA strategy on how to display the APIs by name and/or version, let's put the v3.0 swagger on one page rather than blending them in with the different versions. This will bring us back up to where we were before swagger went offline.

**Temporary Navigation:**
* Add a drop down to API on top nav
  * Docs: goes to current /api-reference/index.html page
  * v3.0 Swagger goes to new /api-swagger page

**Comment by henryyamamoto-concur** [comment]
Moved to new sprint. Testing capability is only open item.

**Comment by howarddierking** [comment]
update: I have the api key text box working and the generated curl requests also work if you paste them into a terminal. Looks like remaining issue is getting the cross origin configuration setup with the hosting ops folks.

**Comment by henryyamamoto-concur** [comment]
Remaining work is being tracked in issue #310
