### ISSUE TITLE
Updates to Partner Resources Page

### ISSUE THREAD

**Issue by serafinj** [concur/developer.concur.com#328]
Hi there, can you please update the files for the resource page? Links to files in Box below.

Apps for Me Release Schedule: https://concur.box.com/s/sel9imho429rpdmdlhcybzq6k1axe2se
App Center Partner Listing Form: https://concur.box.com/s/y3u8guavx9r6ycdtsyo7ghil4d3mzppq
App Center PR Toolkit: https://concur.box.com/s/9ab5upu8uxpltcnm3br4v1uywng2po19
App Center FAQ’s: https://concur.box.com/s/cmj712ma2pc1kmuboeh0520kh0i1pa6l
App Center Lead Submission Process: https://concur.box.com/s/nz7pqvfe4aijbdodv29kkb8fvr8ozwuq
Enabling Apps – Client Facing Guide : https://concur.box.com/s/ngt9gwh9n99wqxcoim3a0drfna7dnab8

Also, under Enabling Apps Guide - spacing is off on this section. Can you push "Share this..." to the next line?

**Comment by henryyamamoto-concur** [comment]
I updated the docs attached to the issue (#328). One doc needed to be renamed to match the existing doc: app_center_faqs_client_facing.pdf

One issue about fixing Enabling Apps Guide was not changed. The space is the same as the others on the page and there is no line break. It could be because this sub-head is longer than others that it doesn't look right?

**Comment by serafinj** [comment]
Thank you Henry! Hmmm, the spacing looked off in my phone but now it looks fine on my laptop. All set!
