### ISSUE TITLE
SPIKE: Review feasibility of adding "Run in Postman" button to Dev Center docs

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#396]
**User story:** As a developer, I would like to the ability to click on a button to run a collection of endpoints, so that I can explore and make test calls using Concur APIs.

Analyze ways we can expose this feature on api reference and/or api explorer pages. I'm waiting on documentation to pass a token over.

http://www.getpostman.com/docs/run_button

**Comment by henryyamamoto-concur** [comment]
Additional info from Postman:

You can use Environments to programmatically input user credentials when using the Run in Postman button. This can be done using the Environment Sharing API.

This is applicable when the API consumer is signed in on the XYZCompany.com's API documentation, with the auth_token stored within the cookie. The publisher can use Environment Sharing API - as defined below - to pass the auth_token to the user's Postman App by simply clicking the Run in Postman button. The script creates an _pm Javascript on the page it is embedded in.

Note: This only works with HTML pages, and not Markdown.

There are 2 ways to generate an environment by calling the API,

_pm('env.create', 'xyz.com', { url: 'http://localhost:1337', auth_token: '1234xyzd' }); // xyz.com = Environment NameOR
_pm('env.create', 'xyz.com', [{ key: 'url', value: 'http://localhost:1337', enabled: true}, {key: 'auth_token', value: '1234xyzd', enabled: false}]); // Enabled false disables the specific key by default
When a User clicks the Run in Postman button, it'll import the collection and the environment (if initialized using _pm function) in the consumer's app.

**Comment by merittrompeter** [comment]
So I think we can half-implement this at the moment.

We can definitely set up collections and add a button that opens postman up with the correct collection preloaded - but it wouldn't be read to use yet.

The problem is with authorization.  The environment sharing API tool postman provides is pretty nifty. However, in order to utilize it we need to have our users logged in on the developer.concur.com.

We could provide instructions on how user could create an an authorized testing environment locally. 
Or we could include a header and have them substitute their token for a placeholder string.

But long story short without having them logged in on developer.concur.com it seems as though they would need to have them do some work themselves to authorize their requests.

**Comment by henryyamamoto-concur** [comment]
Let's put info up on how to setup and provide a link near the "run" button.
