### ISSUE TITLE
API Docs organization and standardization

### ISSUE THREAD

**Issue by henryyamamoto-concur** [concur/developer.concur.com#817]
* Automate API parameters
* Automate pulling of static content from a repo - investigate all sources for relevancy and whether it's possible
* Combine above into new layout

**Comment by bhague1281** [comment]
New Layout demos:

* **Technical docs:** https://preview.developer.concur.com/api-reference-deprecated/v1.html
* **API Guides:** https://preview.developer.concur.com/api-guides/

We may want to re-evaluate our doc organization for guides vs. reference, since the 3-column layout works great for technical documentation, but not as well for guides and overviews.

**Comment by bhague1281** [comment]
Other options:

* Use Postman for documentation
* Use API Blueprint for generating documentation
