### ISSUE TITLE
Suppress GET Bulk Users API from the menu in Authentication section

### ISSUE THREAD

**Issue by lokeuei** [concur/developer.concur.com#837]
can you suppress the menu item from the Authentication section? we want the page to be available to only people who have the direct URL.

**Comment by bhague1281** [comment]
Yes. We're going to change the sidebars so that they're represented as YAML files, for these reasons:

1. Allows us more flexibility when it comes to changing page order
2. Allows us to customize page titles and page visibility
3. Build efficiency. Currently, our sidebar code sorts and iterates through all files/folders, which takes a long time when building the site. Our build time averages around 37 seconds. 22 of those seconds involve the sidebar.

Consequently, any new pages will require an addition to the sidebar data files.

**Comment by bhague1281** [comment]
#849 

@lokeuei Can you verify?
